/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ConversationIdRouteImport } from './routes/conversation.$id'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AdminApiRouteImport } from './routes/admin/api'
import { Route as DashboardNicheIndexRouteImport } from './routes/dashboard/niche/index'
import { Route as DashboardNicheHospitalRouteImport } from './routes/dashboard/niche/hospital'
import { Route as DashboardNicheFoodRouteImport } from './routes/dashboard/niche/food'
import { Route as ApiPublicTwilioWebhookRouteImport } from './routes/api.public.twilio-webhook'
import { Route as ApiPublicScheduledRouteImport } from './routes/api.public.scheduled'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api.public.paystack-webhook'
import { Route as ApiPublicMetaWebhookRouteImport } from './routes/api.public.meta-webhook'
import { Route as ApiPublicHealthRouteImport } from './routes/api.public.health'
import { Route as AdminApiSplatRouteImport } from './routes/admin/api.$'
import { Route as DashboardNicheFoodOrdersRouteImport } from './routes/dashboard/niche/food/orders'
import { Route as DashboardNicheFoodMenuRouteImport } from './routes/dashboard/niche/food/menu'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationIdRoute = ConversationIdRouteImport.update({
  id: '/conversation/$id',
  path: '/conversation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApiRoute = AdminApiRouteImport.update({
  id: '/admin/api',
  path: '/admin/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNicheIndexRoute = DashboardNicheIndexRouteImport.update({
  id: '/niche/',
  path: '/niche/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNicheHospitalRoute = DashboardNicheHospitalRouteImport.update({
  id: '/niche/hospital',
  path: '/niche/hospital',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNicheFoodRoute = DashboardNicheFoodRouteImport.update({
  id: '/niche/food',
  path: '/niche/food',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicTwilioWebhookRoute = ApiPublicTwilioWebhookRouteImport.update({
  id: '/api/public/twilio-webhook',
  path: '/api/public/twilio-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScheduledRoute = ApiPublicScheduledRouteImport.update({
  id: '/api/public/scheduled',
  path: '/api/public/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaWebhookRoute = ApiPublicMetaWebhookRouteImport.update({
  id: '/api/public/meta-webhook',
  path: '/api/public/meta-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApiSplatRoute = AdminApiSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminApiRoute,
} as any)
const DashboardNicheFoodOrdersRoute =
  DashboardNicheFoodOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => DashboardNicheFoodRoute,
  } as any)
const DashboardNicheFoodMenuRoute = DashboardNicheFoodMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardNicheFoodRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automation': typeof AutomationRoute
  '/campaigns': typeof CampaignsRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/admin/api': typeof AdminApiRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/conversation/$id': typeof ConversationIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/api/$': typeof AdminApiSplatRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/meta-webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/scheduled': typeof ApiPublicScheduledRoute
  '/api/public/twilio-webhook': typeof ApiPublicTwilioWebhookRoute
  '/dashboard/niche/food': typeof DashboardNicheFoodRouteWithChildren
  '/dashboard/niche/hospital': typeof DashboardNicheHospitalRoute
  '/dashboard/niche/': typeof DashboardNicheIndexRoute
  '/dashboard/niche/food/menu': typeof DashboardNicheFoodMenuRoute
  '/dashboard/niche/food/orders': typeof DashboardNicheFoodOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automation': typeof AutomationRoute
  '/campaigns': typeof CampaignsRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/admin/api': typeof AdminApiRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/conversation/$id': typeof ConversationIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/api/$': typeof AdminApiSplatRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/meta-webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/scheduled': typeof ApiPublicScheduledRoute
  '/api/public/twilio-webhook': typeof ApiPublicTwilioWebhookRoute
  '/dashboard/niche/food': typeof DashboardNicheFoodRouteWithChildren
  '/dashboard/niche/hospital': typeof DashboardNicheHospitalRoute
  '/dashboard/niche': typeof DashboardNicheIndexRoute
  '/dashboard/niche/food/menu': typeof DashboardNicheFoodMenuRoute
  '/dashboard/niche/food/orders': typeof DashboardNicheFoodOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automation': typeof AutomationRoute
  '/campaigns': typeof CampaignsRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/admin/api': typeof AdminApiRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/conversation/$id': typeof ConversationIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/api/$': typeof AdminApiSplatRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/meta-webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/scheduled': typeof ApiPublicScheduledRoute
  '/api/public/twilio-webhook': typeof ApiPublicTwilioWebhookRoute
  '/dashboard/niche/food': typeof DashboardNicheFoodRouteWithChildren
  '/dashboard/niche/hospital': typeof DashboardNicheHospitalRoute
  '/dashboard/niche/': typeof DashboardNicheIndexRoute
  '/dashboard/niche/food/menu': typeof DashboardNicheFoodMenuRoute
  '/dashboard/niche/food/orders': typeof DashboardNicheFoodOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/automation'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/onboarding'
    | '/pricing'
    | '/settings'
    | '/simulator'
    | '/admin/api'
    | '/api/$'
    | '/conversation/$id'
    | '/admin/'
    | '/admin/api/$'
    | '/api/public/health'
    | '/api/public/meta-webhook'
    | '/api/public/paystack-webhook'
    | '/api/public/scheduled'
    | '/api/public/twilio-webhook'
    | '/dashboard/niche/food'
    | '/dashboard/niche/hospital'
    | '/dashboard/niche/'
    | '/dashboard/niche/food/menu'
    | '/dashboard/niche/food/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/automation'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/onboarding'
    | '/pricing'
    | '/settings'
    | '/simulator'
    | '/admin/api'
    | '/api/$'
    | '/conversation/$id'
    | '/admin'
    | '/admin/api/$'
    | '/api/public/health'
    | '/api/public/meta-webhook'
    | '/api/public/paystack-webhook'
    | '/api/public/scheduled'
    | '/api/public/twilio-webhook'
    | '/dashboard/niche/food'
    | '/dashboard/niche/hospital'
    | '/dashboard/niche'
    | '/dashboard/niche/food/menu'
    | '/dashboard/niche/food/orders'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/automation'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/onboarding'
    | '/pricing'
    | '/settings'
    | '/simulator'
    | '/admin/api'
    | '/api/$'
    | '/conversation/$id'
    | '/admin/'
    | '/admin/api/$'
    | '/api/public/health'
    | '/api/public/meta-webhook'
    | '/api/public/paystack-webhook'
    | '/api/public/scheduled'
    | '/api/public/twilio-webhook'
    | '/dashboard/niche/food'
    | '/dashboard/niche/hospital'
    | '/dashboard/niche/'
    | '/dashboard/niche/food/menu'
    | '/dashboard/niche/food/orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AutomationRoute: typeof AutomationRoute
  CampaignsRoute: typeof CampaignsRoute
  ContactsRoute: typeof ContactsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  AdminApiRoute: typeof AdminApiRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ConversationIdRoute: typeof ConversationIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicMetaWebhookRoute: typeof ApiPublicMetaWebhookRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicScheduledRoute: typeof ApiPublicScheduledRoute
  ApiPublicTwilioWebhookRoute: typeof ApiPublicTwilioWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation/$id': {
      id: '/conversation/$id'
      path: '/conversation/$id'
      fullPath: '/conversation/$id'
      preLoaderRoute: typeof ConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api': {
      id: '/admin/api'
      path: '/admin/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof AdminApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/niche/': {
      id: '/dashboard/niche/'
      path: '/niche'
      fullPath: '/dashboard/niche/'
      preLoaderRoute: typeof DashboardNicheIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/niche/hospital': {
      id: '/dashboard/niche/hospital'
      path: '/niche/hospital'
      fullPath: '/dashboard/niche/hospital'
      preLoaderRoute: typeof DashboardNicheHospitalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/niche/food': {
      id: '/dashboard/niche/food'
      path: '/niche/food'
      fullPath: '/dashboard/niche/food'
      preLoaderRoute: typeof DashboardNicheFoodRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/twilio-webhook': {
      id: '/api/public/twilio-webhook'
      path: '/api/public/twilio-webhook'
      fullPath: '/api/public/twilio-webhook'
      preLoaderRoute: typeof ApiPublicTwilioWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scheduled': {
      id: '/api/public/scheduled'
      path: '/api/public/scheduled'
      fullPath: '/api/public/scheduled'
      preLoaderRoute: typeof ApiPublicScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta-webhook': {
      id: '/api/public/meta-webhook'
      path: '/api/public/meta-webhook'
      fullPath: '/api/public/meta-webhook'
      preLoaderRoute: typeof ApiPublicMetaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api/$': {
      id: '/admin/api/$'
      path: '/$'
      fullPath: '/admin/api/$'
      preLoaderRoute: typeof AdminApiSplatRouteImport
      parentRoute: typeof AdminApiRoute
    }
    '/dashboard/niche/food/orders': {
      id: '/dashboard/niche/food/orders'
      path: '/orders'
      fullPath: '/dashboard/niche/food/orders'
      preLoaderRoute: typeof DashboardNicheFoodOrdersRouteImport
      parentRoute: typeof DashboardNicheFoodRoute
    }
    '/dashboard/niche/food/menu': {
      id: '/dashboard/niche/food/menu'
      path: '/menu'
      fullPath: '/dashboard/niche/food/menu'
      preLoaderRoute: typeof DashboardNicheFoodMenuRouteImport
      parentRoute: typeof DashboardNicheFoodRoute
    }
  }
}

interface DashboardNicheFoodRouteChildren {
  DashboardNicheFoodMenuRoute: typeof DashboardNicheFoodMenuRoute
  DashboardNicheFoodOrdersRoute: typeof DashboardNicheFoodOrdersRoute
}

const DashboardNicheFoodRouteChildren: DashboardNicheFoodRouteChildren = {
  DashboardNicheFoodMenuRoute: DashboardNicheFoodMenuRoute,
  DashboardNicheFoodOrdersRoute: DashboardNicheFoodOrdersRoute,
}

const DashboardNicheFoodRouteWithChildren =
  DashboardNicheFoodRoute._addFileChildren(DashboardNicheFoodRouteChildren)

interface DashboardRouteChildren {
  DashboardNicheFoodRoute: typeof DashboardNicheFoodRouteWithChildren
  DashboardNicheHospitalRoute: typeof DashboardNicheHospitalRoute
  DashboardNicheIndexRoute: typeof DashboardNicheIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardNicheFoodRoute: DashboardNicheFoodRouteWithChildren,
  DashboardNicheHospitalRoute: DashboardNicheHospitalRoute,
  DashboardNicheIndexRoute: DashboardNicheIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface AdminApiRouteChildren {
  AdminApiSplatRoute: typeof AdminApiSplatRoute
}

const AdminApiRouteChildren: AdminApiRouteChildren = {
  AdminApiSplatRoute: AdminApiSplatRoute,
}

const AdminApiRouteWithChildren = AdminApiRoute._addFileChildren(
  AdminApiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AutomationRoute: AutomationRoute,
  CampaignsRoute: CampaignsRoute,
  ContactsRoute: ContactsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  AdminApiRoute: AdminApiRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ConversationIdRoute: ConversationIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicMetaWebhookRoute: ApiPublicMetaWebhookRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicScheduledRoute: ApiPublicScheduledRoute,
  ApiPublicTwilioWebhookRoute: ApiPublicTwilioWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
